<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
    <title>Welcome to My Web Application</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f8ff;
            color: #333;
            margin: 0;
            padding: 0;
        }
        header {
            background-color: #4CAF50;
            padding: 20px;
            text-align: center;
            color: white;
        }
        h1 {
            color: #4CAF50;
        }
        p {
            font-size: 1.2em;
            padding: 10px;
        }
        .welcome-message {
            margin: 20px auto;
            padding: 20px;
            background-color: #e0f7fa;
            border-radius: 10px;
            width: 60%;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to My Web Application!</h1>
    </header>
    <div class="welcome-message">
        <p>This is the homepage, dynamically generated by JSP.</p>
        <%
            String username = request.getParameter("username");
            if (username != null) {
                out.println("<p>Hello, <strong>" + username + "</strong>! We're glad to have you here.</p>");
            } else {
                out.println("<p>Hello, Guest! Please provide your username for a personalized experience.</p>");
            }
        %>
    </div>
</body>
</html>
